name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest]        
        include:
          - name: Client
            env: PACKAGE_LOCATION=client
          - name: Server
            env: PACKAGE_LOCATION=server
        node-version: [lts/*]
    runs-on: ${{ matrix.os }}
#     env:
#       PACKAGE_LOCATION: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          cd $PACKAGE_LOCATION
          npm ci
          npm run format
          npm run lint
          npm run build
          npm run test
